_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 19
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.5
            "6": 4.46.1
            "8":
                - 1
                - 5
            "12": 0.18.5
            "13": darwin-arm64
batch_size:
    value: 10
epochs:
    value: 15
learning_rate:
    value: 1e-05
